#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    ports:
#      - 5432:5432
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=passw0rd
#      - POSTGRES_USER=myuser
#      - POSTGRES_DB=mydatabase

version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data:
