DROP TABLE IF EXISTS PROFILE CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

CREATE TABLE "User" (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL
);

CREATE TABLE PROFILE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(20),
    SURNAME VARCHAR(20),
    DATE_OF_BIRTH DATE,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(20),
    GENDER VARCHAR(20),
    PASSWORD VARCHAR(100)
);

ALTER TABLE PROFILE
ADD CONSTRAINT PROFILE_PK
FOREIGN KEY (ID) REFERENCES "User" (ID);